baseURL = "https://joshuab.xyz/"
languageCode = "en-us"
title = "JoshuaB.xyz"
theme = "aether"
#googleAnalytics = "Your google analytics tracking ID - optional"
#disqusShortname = "Your shortname for Disqus - optional"

[params]
brand = "JoshuaB.xyz"
description = "The online home of Joshua B."
homeimg = "/images/homebg.jpg"
bgimg = "/images/bg.jpg"
rssinmenu = false
